---
title: "R Notebook"
output: html_notebook
---

```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)

# Graphics
library(ggplot2)
library(modelsummary)
library(stargazer)

#Statistics
library(plm)

# Geographic
library(sf)
library(sidrar)
library(geobr)
```

# Local Prices

## Small

```{r}
a1 <- cattle_sales_census %>%
  replace(is.na(.), 0) %>% 
  mutate(average_price =  
           (
            # sales_value_big_slaughter +
            sales_value_small
           )/
           (
            # heads_sold_big_slaughter +
            heads_sold_small  
           )
         ) %>% 
  drop_na(average_price) 

```

```{r}
print("Big slaughter")
summary(a$average_price)
```

```{r}
a1 %>% 
  ggplot(., aes(x = average_price)) +
  geom_histogram(fill = "grey", color = "white", bins = 30) +
  labs(title = "Local price Distribution (in R$ 1000)", 
       x = "Values", 
       y = "Frequency") +
  theme_minimal()
```

## Big

```{r}
a2 <- cattle_sales_census %>%
  replace(is.na(.), 0) %>% 
  mutate(average_price =  
           (
            sales_value_big_slaughter
            # sales_value_small
           )/
           (
            heads_sold_big_slaughter
            # heads_sold_small  
           )
         ) %>% 
  drop_na(average_price) 

```

```{r}
print("Big slaughter")
summary(a$average_price)
```

```{r}
a2 %>% 
  ggplot(., aes(x = average_price)) +
  geom_histogram(fill = "grey", color = "white", bins = 30) +
  labs(title = "Local price Distribution (in R$ 1000)", 
       x = "Values", 
       y = "Frequency") +
  theme_minimal()
```

# Map of local prices

## Prices from small

```{r}
b1 <- left_join(
    
  municipalities %>%  
    filter(
      code_state %in% amazon_states
    ),
  
  a1 %>% 
    select(
      city_code, average_price
    ),
  
  by = c("code_muni" = "city_code")
)

ggplot() +
  geom_sf(
    data = b1,
    aes(
      geometry = geom,
      fill = average_price
      ),
    color= NA, size=.15
    ) +
  scale_fill_distiller(
    palette = "Greens", direction = 1, 
    name='Average Price'
    ) +
  theme_minimal() +
  theme(
    axis.title=element_blank(),
    axis.text=element_blank(),
    axis.ticks=element_blank()
    )

```

## Prices from big

```{r}
b2 <- left_join(
    
  municipalities %>%  
    filter(
      code_state %in% amazon_states
    ),
  
  a2 %>% 
    select(
      city_code, average_price
    ),
  
  by = c("code_muni" = "city_code")
)

ggplot() +
  geom_sf(
    data = b2,
    aes(
      geometry = geom,
      fill = average_price
      ),
    color= NA, size=.15
    ) +
  scale_fill_distiller(
    palette = "Greens", direction = 1, 
    name='Average Price'
    ) +
  theme_minimal() +
  theme(
    axis.title=element_blank(),
    axis.text=element_blank(),
    axis.ticks=element_blank()
    )

```

# Local prices vs Transportation costs

```{r}
a <- left_join(
  sh_distance %>%  
    filter(
      code_state %in% amazon_states
    ),
  
  a2 %>% 
    select(
      city_code, average_price
    ),
  
  by = c("code_muni" = "city_code")
  ) %>% 
  left_join(
    transport_cost_muni %>%
      as_tibble() %>% 
      select(
        code_muni, transport_cost
      ),
    by = join_by(code_muni)
  ) %>% 
  mutate(
    transport_cost = transport_cost/1000 
  )
```

## Regressions Sh and Tc

```{r}
m_sh <- lm(
  data = a,
  log(average_price) ~ distance_to_sh
)

m_tc <- lm(
  data = a,
  log(average_price) ~ transport_cost
)

m_both <- lm(
  data = a,
  log(average_price) ~ log(transport_cost) + log(distance_to_sh)
)

# Results
summary(m_sh)
summary(m_tc)
summary(m_both)
```

# Cattle prices

```{r}
ypc <- prices_cattle %>% 
  mutate(
    date = as_date(date, format = "%d/%m/%Y")
  ) %>% 
  group_by( 
    year = year(date)
  ) %>% 
  summarise(
    price = mean(price_brl)
  )
```

```{r}
p_2017 <- ypc %>% 
  filter(year == 2017) %>% 
  select(price) %>% 
  as.numeric()
```

```{r}
y <-  inner_join(
  b2 %>% 
    drop_na(average_price),
  
  cattle_heads_ppm %>% 
    drop_na(cattle_heads) %>% 
    select(
      year, city_code, cattle_heads
    ),
  
  by = c("code_muni" = "city_code")
  ) %>% 
  mutate(
    year = as.numeric(year),
    muni_state = paste0(name_muni, "-", abbrev_state),
    name_muni = as.factor(muni_state),
    abbrev_state = as.factor(abbrev_state)
  ) %>% 
  left_join(
    ypc,
    by = "year"
  ) %>% 
  mutate(
    local_price = price * average_price*1000 / p_2017
  ) %>% 
  select(
    muni_state,
    abbrev_state,
    year,
    cattle_heads,
    local_price
  ) %>% 
  filter(
    year >= 2005
  ) 
```

# Regression

```{r}
y_panel <- pdata.frame(
  y, 
  index=c("muni_state","year"),
  drop.index=FALSE, 
  row.names=TRUE)
```

```{r}
model <- plm(
  cattle_heads ~ local_price + lag(local_price, 1) | lag(local_price, 1:2) ,
  data = y_panel,
  model = "within",
  effect = "individual"
  )

summary(model)
```

```{r}
delta = 1/as.vector(model$coefficients)[2]*1/0.9
phi = - delta * as.vector(model$coefficients)[1]

print(phi)
```
