---
title: "Price Data"
author: "Shai Vaz"
date: "May 2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(readxl)
library(lubridate)
```

# CEPEA Data imports

## Cattle Prices

```{r}
prices_cattle <- read_xlsx(
  path = "../Inputs/prices_cattle.xlsx",
  sheet = "Plan 1",
  col_names = c("date","price_brl","price_usd"),
  skip = 4
  )
```

## Soybeans Prices

```{r}
prices_soybeans <- read_xlsx(
  path = "../Inputs/prices_soybeans.xlsx",
  sheet = "Plan 1",
  col_names = c("date","price_brl","price_usd"),
  skip = 4
  )
```

## Maize Prices

```{r}
prices_maize <- read_xlsx(
  path = "../Inputs/prices_maize.xlsx",
  sheet = "Plan 1",
  col_names = c("date","price_brl","price_usd"),
  skip = 4
  )
```

## Chicken prices

```{r}
prices_chicken <- read_xlsx(
  path = "../Inputs/prices_chicken.xlsx",
  sheet = "Plan 1",
  col_names = c("date","price_brl","price_usd"),
  skip = 4
  )
```

# Consolidation

## Prices during census years

Reference period for the 2017 census is ***Oct 1st 2016*** through ***Sep 30th 2017***. For the 2006 census, it is ***Jan 1st 2006*** through ***Dec 31st 2006.***

```{r}
cattle_prices_cepea_in_census_years <- prices_cattle |> 
  mutate(
    date = as_date(date, format = "%d/%m/%Y"),
    census_year = case_when(
      date >= "2016-10-01" & date <= "2017-09-30" ~ 2017,
      date >= "2017-10-01" & date <= "2018-09-30" ~ 2018,
      date >= "2006-01-01" & date <= "2006-12-31" ~ 2006,
      date >= "2007-01-01" & date <= "2007-12-31" ~ 2007,
      .default = NA )
  ) |>
  summarise(
    mean_price = mean(price_brl),
    max_price = max(price_brl),
    min_price = min(price_brl),
    sd_price = sd(price_brl),
    .by = census_year
  ) |> 
  drop_na()
```

## Join Dataframes

```{r}
national_prices <- full_join(
  # Yearly cattle prices
  prices_cattle |> 
    mutate(
      date = as_date(date, format = "%d/%m/%Y")
    ) |> 
    group_by( 
      year = year(date)
    ) |> 
    summarise(
      cattle_price = mean(price_brl, na.rm = T),
      cattle_price_usd = mean(price_usd, na.rm = T)
    ),
  # Yearly soybean prices
  prices_soybeans |> 
    mutate(
      date = as_date(date, format = "%d/%m/%Y")
    ) |> 
    group_by( 
      year = year(date)
    ) |> 
    summarise(
      soy_price = mean(price_brl),
      soy_price_usd = mean(price_usd)
    ),
  
  by = "year"
  ) |> 
  full_join(
  # Yearly maize prices
  prices_maize |> 
    mutate(
      date = as_date(date, format = "%d/%m/%Y")
    ) |> 
    group_by( 
      year = year(date)
    ) |> 
    summarise(
      maize_price = mean(price_brl),
      maize_price_usd = mean(price_usd)
    ),
  
  by = "year"
  ) |> 
  full_join(
  # Yearly chicken prices
  prices_chicken |> 
    mutate(
      date = as_date(date, format = "%d/%m/%Y")
    ) |> 
    group_by( 
      year = year(date)
    ) |> 
    summarise(
      chicken_price = mean(price_brl),
      chicken_price_usd = mean(price_usd)
    ),
  
  by = "year"
  )
```

# Generate RDSs

```{r}
bulk_write_rds(
  national_prices,
  cattle_prices_cepea_in_census_years
  )
```
