---
title: "Transportation Costs"
author: "Shai Vaz"
date: "May 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(readxl)

# Graphics
library(ggplot2)

# Geographic
library(sf)
library(terra)
```

# Importing

## Transportation Costs

```{r}
transport_cost <- rast(
  x = "../Inputs/cost_raster_raster_proj.tif"
  )
```

## Municipality Seats

```{r}
municipalities_tc <- read_rds(
  file = "../Variables/municipalities.rds"
  ) %>%
  # match crs with raster
  st_transform(
    crs(transport_cost)
  ) %>%
  # save with terra
  vect()
```

## Conservation Units



## Indigenous Lands



# Removing protected areas

Here I'll remove conservation units and indigenous lands from the cost raster.


# Masking TC by municipality

```{r}
transport_cost_muni <- extract(
  # extract from raster
  transport_cost, 
  municipalities_tc, 
  fun = mean, 
  na.rm = TRUE,
  touches = TRUE,
  bind = TRUE) %>% 
  # return to sf format
  st_as_sf() %>% 
  rename(
    transport_cost = cost_raster_raster_proj
  ) %>% 
  # reverse CRS to standard
  st_transform(
    st_crs(municipalities)
  ) %>% 
  # filter to amazon
  filter(
    code_state %in% amazon_states
  )
```

## Map

```{r}
ggplot() +
  geom_sf(
    data = transport_cost_muni,
    aes(
      geometry = geometry,
      fill = transport_cost
      ),
    color= NA
    ) +
  theme_minimal() +
  theme(
    axis.title=element_blank(),
    axis.text=element_blank(),
    axis.ticks=element_blank()
    )
```
# Generate RDS

```{r}
write_rds(
  transport_cost_muni,
  file = "../Variables/transport_cost_muni.rds"
)
```

