---
title: "Data Unification"
author: "Shai Vaz"
date: "May 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(readxl)

# Graphics
library(ggplot2)

# Geographic
library(sf)

# Statistics
library(plm)
```

# Importing files

```{r}
# cattle_heads_ppm
national_prices
cattle_prices_2017_census
cattle_price_2017_cepea
# municipalities
sh_distance
# transport_cost_muni
# pasture_cover
```

# Intensity per municipality

```{r}
pasture_intensity <- inner_join(
  cattle_heads_ppm,
  
  pasture_cover,
  by = c("code_muni", "year")
  ) %>% 
  mutate(
    intensity = cattle_heads/pasture_cover
  )
```

```{r}
summary(pasture_intensity$intensity)
```

# Local prices panel

Provisional!!!!

```{r}
panel <- inner_join(
  cattle_prices_2017_census %>% 
    drop_na(average_price),
  
  pasture_intensity %>% 
    drop_na(intensity) %>% 
    select(
      year, 
      code_muni, 
      muni_state, 
      cattle_heads, 
      pasture_cover, 
      intensity
    ),
  
  by = "code_muni"
  ) %>% 
  mutate(
    year = as.numeric(year),
    muni_state = as.factor(muni_state),
    name_state = as.factor(name_state)
  ) %>% 
  left_join(
    national_prices,
    by = "year"
  ) %>% 
  mutate(
    local_price = cattle_price*average_price*1000/cattle_price_2017_cepea,
    chicken_price = chicken_price*1000 #in ton
  ) %>% 
  select(
    year, 
    code_muni, 
    muni_state,
    name_state,
    cattle_heads, 
    pasture_cover, 
    intensity,
    local_price,
    chicken_price
  ) %>% 
  filter(
    year >= 2005
  ) %>% 
  left_join(
    sh_distance %>%
      as_tibble() %>% 
      select(code_muni, distance_to_sh),
    by = "code_muni"
  ) %>% 
  mutate(
    iceberg_cost = 1/distance_to_sh
  )
```

## Panel Linear Model

```{r}
y <- pdata.frame(
  panel, 
  index=c("muni_state","year"),
  drop.index=FALSE, 
  row.names=TRUE) %>% 
  mutate(
    shifter = plm::lag(chicken_price,1)*iceberg_cost
  )
```

# Regressions

## First stage

```{r}
s1 <- plm(
  local_price ~ lag(chicken_price,1:2),
  data = y,
  model = "within",
  effect = "individual"
  )

summary(s1)
```

## Second Stage

### Baseline

* chicken price in dollar

```{r}
model_1 <- plm(
  cattle_heads ~ local_price + lag(local_price) | . - local_price + lag(chicken_price,1:2):iceberg_cost,
  data = y,
  model = "within",
  effect = "individual"
  )

summary(model_1)
```

```{r}
delta = 1/as.vector(model_1$coefficients)[2]*1/0.9
phi1 = - delta * as.vector(model_1$coefficients)[1]

print(phi1)
```

### Controlling for pasture area

```{r}
model_2 <- plm(
  cattle_heads ~ local_price + lag(local_price) + pasture_cover | . - local_price - pasture_cover + lag(chicken_price,1:2):iceberg_cost + lag(pasture_cover),
  data = y,
  model = "within",
  effect = "individual"
  )

summary(model_2)
```

```{r}
delta = 1/as.vector(model_2$coefficients)[2]*1/0.9
phi1 = - delta * as.vector(model_2$coefficients)[1]

print(phi1)
```

### Baseline in logs

```{r}
model_3 <- plm(
  log(cattle_heads) ~ local_price + lag(local_price) | . - local_price + lag(chicken_price,1:2):iceberg_cost,
  data = y,
  model = "within",
  effect = "individual"
  )

summary(model_3)
```

```{r}
delta = 1/as.vector(model_3$coefficients)[2]*1/0.9
phi1 = - delta * as.vector(model_3$coefficients)[1]

print(phi1)
```

### Log and time trend


```{r}
model_4 <- plm(
  log(cattle_heads) ~ local_price + lag(local_price) + as.numeric(year) | . - local_price + lag(chicken_price,1:2):iceberg_cost,
  data = y,
  model = "within",
  effect = "individual"
  )

summary(model_4)
```

```{r}
delta = 1/as.vector(model_4$coefficients)[2]*1/0.9
phi1 = - delta * as.vector(model_4$coefficients)[1]

print(phi1)
```

### Level, pasture and time trend


```{r}
model_5 <- plm(
  cattle_heads ~ local_price + lag(local_price) + pasture_cover + as.numeric(year) | . - local_price + lag(chicken_price,1:2):iceberg_cost,
  data = y,
  model = "within",
  effect = "individual"
  )

summary(model_5)
```

```{r}
delta = 1/as.vector(model_5$coefficients)[2]*1/0.9
phi1 = - delta * as.vector(model_5$coefficients)[1]

print(phi1)
```


# Testing Outliers    

```{r}
a <- panel %>% 
  select(1:5) %>%
  group_by(muni_state) %>% 
  mutate(
    lag_cattle_heads = dplyr::lag(cattle_heads),
    cattle_heads = cattle_heads,
    lead_cattle_heads = dplyr::lead(cattle_heads),
    
    lag_var_heads = cattle_heads/dplyr::lag(cattle_heads)-1,
    
    lead_var_heads = dplyr::lead(cattle_heads)/cattle_heads-1,

    z_score = (cattle_heads - mean(cattle_heads, na.rm = TRUE))/sd(cattle_heads)
  ) %>% 
  filter(
    year > 2005
  )
```

```{r}
quantile(a$z_score, c(0.0001, 0.0005, 0.001, 0.999, 0.9995, 0.9999), na.rm=TRUE)
```

```{r}
b <- a %>% 
  filter(
     z_score < -3.2 # Novo Progresso - PA
     | z_score > 3.4 
  )
```

```{r}
P = ecdf(a$z_score)
(1-P(3.4))*100 + P(-3.2)*100 - 1
```

