---
title: "Data Unification"
author: "Shai Vaz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(readxl)
library(forcats)

# Graphics
library(ggplot2)

# Geographic
library(sf)

# Econometrics
library(fixest)
library(ivreg)
library(stats)

# Personal functions
source("../Functions/bulk_rds.R")
```

# Importing files

```{r}
bulk_read_rds(
  # prices
  national_prices,
  cattle_prices_cepea_in_census_years,
  ipca_census_years,
  # census data
  agg_census_data,
  # survey data
  cattle_heads_ppm,
  # instruments
  ssiv,
  # controls
  tc_by_amc,
  ma_long,
  si_by_amc,
  # mapbiomas
  land_cover_agg,
  transition_agg,
  past_qual
  )
```

# Joining quantities, prices and shifters

```{r}
joined_data <- left_join(
  # first I join shifters with prices
  # then I extract data from t+1
  ssiv |> 
    select(code_amc, year, area_amc, ssiv),
  
  cattle_prices_cepea_in_census_years,
  
  by = c("year" = "census_year")
  ) |> 
  ########## get next period prices and shifters
  mutate(
    mean_price_2 = if_else(
      year == 2006 | year == 2017,
      lead(mean_price),
      NA),
    
    mean_nominal_price_2 = if_else(
      year == 2006 | year == 2017,
      lead(mean_nominal_price),
      NA),
    
    ssiv_2 = if_else(
      year == 2006 | year == 2017,
      lead(ssiv),
      NA)
  ) |>
  ############ join with census data
  right_join(
    agg_census_data,
    
    by = c("code_amc", "year")
  ) |>
  ############ join with inflation
  left_join(
    ipca_census_years,
    
    by = c("year" = "census_year")
  ) |> 
  ############ deflate and project ahead local prices
  mutate(
    local_price = av_price_slaughter*1000,
    
    # *(index_2022/index)
    local_price_2 = av_price_slaughter
                    *(mean_nominal_price_2/mean_nominal_price)*1000,
  ) |> 
  ############# include controls
  left_join(
    tc_by_amc,
    by = "code_amc"
  ) |> 
  left_join(
    ma_long,
    by = c("code_amc", "year")
  ) |> 
  left_join(
    si_by_amc,
    by = "code_amc"
  ) |> 
  ############ include land use
  left_join(
    land_cover_agg,
    
    by = c("code_amc", "year")
  ) |> 
  ############ include pasture quality
  left_join(
    past_qual,
    by = c("code_amc", "year")
  ) 
```


# Regression

## Todo mundo

```{r}
iv <- feols(
  data = joined_data,
  cattle_heads_big/area_amc ~
    ma_norm
  + ma_norm:I(main_biome=="amazonia")
  + si_mean
  + si_mean:I(main_biome=="amazonia")
  + high_share
  + I(pasture/area_amc)
  | sw(1,main_biome,code_state)
  | local_price + local_price_2 ~ ssiv + ssiv_2,
  panel.id = c("code_amc","year"),
  cluster = "code_amc"
  )

etable(iv, stage=2, fitstat = ~ n + f + ivf)
```


```{r}
ols <- feols(
  data = joined_data,
  cattle_heads_big/area_amc ~
    local_price
  + local_price_2
  + ma_norm 
  + si_mean
  + high_share
  + I(pasture/area_amc)
  | sw(1,main_biome,code_state, code_amc),
  panel.id = c("code_amc","year"),
  cluster = "code_amc"
  )

etable(ols, stage=2, fitstat = ~ n + f + wf + r2 + wr2 + ar2)
```


## Tables

```{r}
etable(
    m1,
    stage = 2,
    tex = T,
    fitstat = ~ n + f + ivfall
    )
```


```{r}
etable(
    m2,
    stage = 2,
    tex = T,
    fitstat = ~ n + f + ivfall
    )
```

```{r}
etable(
    m2,
    stage = 1,
    tex = T,
    fitstat = ~ n + f + ivfall
    )
```



## amazonia

```{r}
feols(
  data = joined_data,
  cattle_heads_big/area_amc ~ 1 |main_biome + code_state| local_price + local_price_2 ~ ssiv + ssiv_2,
  ) |> 
  etable()
```

## cerrado

```{r}
feols(
  data = joined_data |> filter(code_biome == 3),
  cattle_heads_big ~ 1 | local_price + local_price_2 ~ ssiv + ssiv_2
  ) |> 
  etable()
```

# Diagnostics

```{r}
a <- joined_data |> 
  mutate(
    fe = as_factor(code_amc),
    fe_2 = as_factor(main_biome)
  ) |> 
  drop_na() |> 
  filter(
    cattle_heads_big != 0
  )
```

```{r}
first_stage1 <- lm(local_price ~ ssiv, data = a)
first_stage2 <- lm(local_price_2 ~ ssiv_2, data = a)

# Extract predicted values
a$local_price_hat <- predict(first_stage1)
a$local_price_2_hat <- predict(first_stage2)
```

```{r}
iv_model <- ivreg(
  cattle_heads_big ~ local_price_hat + local_price_2_hat:fe_2 + fe_2, 
  data = a
)


summary(iv_model)
```

## FE without IV

```{r}
feols(
  data = a,
  cattle_heads_big ~ local_price + local_price_2 | fe + year
  ) |> 
  etable()
```

# Extensive margin

```{r}
ext_data <- transition_agg |> 
  select(
    code_amc,
    year = year_to,
    rho_1 = natural_pasture
  ) |> 
  mutate(
    rho_2 = lead(rho_1),
    .by = code_amc
  ) |> 
  right_join(
    joined_data,
    by = c("code_amc", "year")
  ) |>
  filter(
    rho_1 != 0 &
    rho_1 != 1 &
    rho_2 != 0 
  ) |> 
  mutate(
    y = log(rho_1/(1-rho_1)) - 0.9* log(rho_2),
    
    x1 = 0.45*(cattle_heads_big**2)/10000000,
    
    x2 = 0.45*(cattle_heads_big/area_amc)**2
  ) |> 
  mutate(
    x3 = 0.45*(cattle_heads/area_amc)**2
  )
```


## Reg

```{r}
feols(
  data = ext_data,
  y ~ x2
  + ma_norm
  + (si_q1_mean + si_q2_mean + si_q3_mean + si_q4_mean)
  + high_share
  | sw(main_biome, code_state, code_amc),
  cluster = "code_amc"
  ) |>  
  etable(fitstat = ~ n + f + f.p + wf + wf.p + r2 + ar2 + wr2)
```

## PPM version


```{r}
bulk_read_rds(muni_to_amc)

ext_ppm <- cattle_heads_ppm |> 
  left_join(
    muni_to_amc |> select(-name_muni),
    by = join_by(code_muni)
  ) |> 
  summarise(
    .by = c("code_amc", "year"),
    
    cattle_heads = sum(cattle_heads, na.rm = TRUE),
    main_biome = unique(main_biome),
    code_biome = unique(code_biome)
  ) |> 
  left_join(
    ma_long |> 
      filter(year == 2006) |> 
      select(-year_ma, -year),
    
    by = "code_amc"
  ) |> 
  mutate(
    year = as.numeric(year)
  ) |> 
  left_join(
    by = join_by(code_amc, year), 
    
    transition_agg |>
      select(
          code_amc,
          year = year_to,
          rho_1 = natural_pasture
      ) |> 
      mutate(
        rho_2 = lead(rho_1),
        .by = code_amc
    )
  ) |> 
  left_join(
    by = c("code_amc", "year"),
    
    ssiv |> 
      select(
      year, code_amc, psi, area_amc, ssiv  
      ) |> 
      mutate(
        ssiv2 = lead(ssiv),
        .by = "code_amc"
      )
  ) |> 
  mutate(
    y = log(rho_1/(1-rho_1)) - 0.9* log(rho_2),
    
    x1 = 0.45*(cattle_heads**2),
    
    x2 = 0.45*(cattle_heads/area_amc)**2
  ) |> 
  filter(
    year > 2006,
    year < 2022
  ) |> 
  mutate(
    fe = as.factor(code_amc)
  ) |> 
  left_join(
    past_qual,
    by = c("code_amc", "year")
  ) |> 
  mutate(
    x3 = 0.45*(cattle_heads/total)**2
  )
```

## OLS with PPM

```{r}
feols(
  data = ext_ppm,
  y ~ x2
  + ma_norm
  + ma_norm:I(main_biome=="amazonia")
  + high_share
  | sw(main_biome, code_state, code_amc),
  cluster = "code_amc"
  ) |> 
  etable( fitstat = ~ n + f + f.p + wf + wf.p + r2 + ar2 + wr2)
```
## IV with PPM

```{r}
feols(
  data = ext_ppm,
  y ~ 1 
  + ma_norm
  + ma_norm:I(main_biome=="amazonia")
  + high_share
  | sw(main_biome, code_state, code_amc)
  | x2 ~ ssiv,
  cluster = "code_amc"
  ) |> 
  etable(fitstat = ~ n + f + f.p + ivf + ivf.p)
```

